if [ -f $HOME/.bashrc ]; then
  . $HOME/.bashrc
fi

if [ -f $HOME/.bash_completion ]; then
  . $HOME/.bash_completion
fi

if [ -f $HOME/.git-completion.bash ]; then
  . $HOME/.git-completion.bash
fi

if [ -f $HOME/.bash_extended ]; then
  . $HOME/.bash_extended
fi